-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versione server:              5.5.16 - MySQL Community Server (GPL)
-- S.O. server:                  Win64
-- HeidiSQL Versione:            8.3.0.4738
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dump della struttura del database agenzie
CREATE DATABASE IF NOT EXISTS `agenziedb` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `agenziedb`;

CREATE TABLE IF NOT EXISTS agenzie(
   Codice             INTEGER  NOT NULL PRIMARY KEY 
  ,Nome_Agenzia       VARCHAR(36) NOT NULL
  ,Nome_Referente     VARCHAR(28) NOT NULL
  ,Preventivi_01      BIT  NOT NULL
  ,Num_Prenotazioni   INTEGER  NOT NULL
  ,Fatturato_netto    INTEGER  NOT NULL
  ,Cicloturismo       BIT  NOT NULL
  ,Enogastronomia     BIT  NOT NULL
  ,LGBT               BIT  NOT NULL
  ,Pet_friendly       BIT  NOT NULL
  ,Piccoli_gruppi     BIT  NOT NULL
  ,Lune_di_miele      BIT  NOT NULL
  ,ArteCultura        BIT  NOT NULL
  ,BenessereBellezza  BIT  NOT NULL
  ,MICE               BIT  NOT NULL
  ,Prezzo             INTEGER  NOT NULL
);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (1,'A Voi D''Oiseau','Abbie McCarthy',0,0,0,0,0,0,0,1,0,1,0,0,1115);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (2,'Aaa Travel Agency','Abdul-Ahad Bakr Nader',1,1,2700,0,1,0,0,1,0,1,0,0,1321);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (3,'Above N Beyond Travels','Abdul-Qadir Salamah Nazari',0,0,0,0,0,0,0,1,1,0,1,0,906);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (4,'Abracadabra','Abi Medrano Montez',0,0,0,0,1,1,0,0,1,1,1,0,1519);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (5,'Action-Adventure Travel','Abida Juwan Bazzi',0,0,0,1,1,1,0,1,1,0,1,1,376);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (6,'Advance Adventure','Abigail Feakes',0,0,0,1,1,0,1,0,0,1,0,1,2611);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (7,'Adventure As A Lifestyle','Aceline Tétrault',0,0,0,0,1,1,1,0,0,0,1,1,2321);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (8,'Adventures','Adalgiso Sabbatini',0,0,0,1,0,0,0,1,1,1,1,0,665);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (9,'Adventurous Travelers','Adele Sagese',0,0,0,0,0,1,1,0,0,0,1,1,1333);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (10,'Agence Bougeotte','Agate Quiron',0,0,0,0,1,0,1,1,0,1,0,0,2893);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (11,'Agenzia Resort','Agostina Li Fonti',1,0,0,1,1,1,1,0,1,0,0,0,2058);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (12,'Agenzia Tropico','Aimee Mitchell',0,0,0,0,1,0,1,0,0,1,0,1,2593);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (13,'Air Italia','Al Tijani ''Awf Koury',0,0,0,0,0,0,0,0,0,0,0,1,436);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (14,'Air Puglia','Alda Conti',1,3,2900,0,0,0,1,0,0,1,1,0,405);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (15,'Airsea Travel','Ale Abrego Garza',0,0,0,0,1,1,0,0,0,1,0,1,2462);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (16,'Alaspro','Aleandro Marino',0,0,0,0,1,0,0,1,1,1,0,1,367);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (17,'Alastrip','Aleksander Zambrano Olivárez',0,0,0,0,0,1,1,1,0,1,0,0,1481);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (18,'All That Travel','Alex Souza Martins',0,0,0,1,1,0,0,0,0,1,0,0,1259);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (19,'Arianne Tourisme','Alexander Graham',1,1,1400,0,1,0,1,0,1,0,1,0,2283);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (20,'Asia Travels Pty Ltd','Alfonso De Luca',0,0,0,1,0,0,0,0,0,1,1,1,2368);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (21,'Atelier Reisen','Alfredina Bellucci',0,0,0,0,1,0,0,0,1,0,1,1,1134);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (22,'Atral Viajes','Alicia Hargreaves',0,0,0,0,1,0,0,1,0,1,1,1,342);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (23,'Atrapalo','Alicia James',1,3,4070,0,1,1,0,0,1,0,0,1,1353);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (24,'Autotral Travel','Amber Mullaly',1,0,0,0,0,1,1,1,0,1,0,1,1584);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (25,'Avenues Of The World','Ambra Longo',0,0,0,0,0,0,0,1,0,0,0,0,862);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (26,'Bagaglio A Mano','Ana Delgado Ortega',0,0,0,0,1,1,0,1,1,0,0,0,641);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (27,'Best Travel','Ana Ferreira Alves',0,0,0,0,1,0,0,1,0,0,1,1,2476);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (28,'Beyond D Sea Travels','Andrea Urner',0,0,0,1,1,0,0,0,1,0,0,0,2723);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (29,'Beyond The Pillar Of Hercules','Annett Kalb',0,0,0,1,1,1,1,0,1,1,1,1,451);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (30,'Conquest Travel Agency','Artus Lanteigne',0,0,0,0,0,1,0,0,0,0,1,1,289);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (31,'Cruise N Travel Experts','Austin Ashton',0,0,0,0,1,1,0,1,1,1,1,1,2389);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (32,'Curated Calendar','Barbara C. Franco',1,1,1500,1,1,1,1,1,0,0,0,0,1964);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (33,'Do Travel','Basilio Bianchi',0,0,0,0,1,0,1,0,0,1,1,0,877);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (34,'D-Relax','Benvenuto Zito',0,0,0,1,1,0,0,1,1,0,0,1,733);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (35,'Emisfero Nord','Callum Bryant',0,0,0,0,1,1,1,1,0,0,0,1,1557);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (36,'Flaming Pheonix Travel','Carina Aguilera Saldana',0,0,0,1,0,1,0,1,1,0,1,0,286);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (37,'Fly And Dream','Carl S. Franklin',0,0,0,1,0,1,0,1,1,0,0,1,747);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (38,'Getaways Gateway','Carla Martins Silva',1,0,0,1,1,0,1,0,1,1,1,0,1883);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (39,'Giro 360','Connie R. Krueger',0,0,0,1,0,0,0,1,1,1,1,0,1613);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (40,'Globehunters','Doda Monaldo',0,0,0,0,0,0,1,1,0,1,0,0,1463);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (41,'Go Go Travel','Dominic Warren',1,0,0,0,1,0,1,0,1,1,1,1,2370);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (42,'Guida Viaggi','Donald A. Long',0,0,0,0,0,1,1,1,1,1,0,0,1553);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (43,'Homewardhols','Dylan Miller',0,0,0,0,1,1,0,0,1,1,0,0,1324);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (44,'I Viaggi Dell''Eden','Edna B. Lee',0,0,0,1,1,1,0,0,1,1,1,1,416);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (45,'Instant Itinerary','Elliot George',0,0,0,0,0,0,0,0,1,0,1,1,1438);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (46,'International Sun Travel Agency','Emanuela Iadanza',0,0,0,0,0,0,1,1,1,1,0,0,785);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (47,'Into Itineraries','Emilly Barros Alves',0,0,0,0,1,0,1,1,1,0,1,0,790);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (48,'Jet Set Go','Emily Castro Oliveira',0,0,0,1,1,0,0,0,1,0,0,0,2097);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (49,'Jet Set Travel','Emmanuelle Paulet',0,0,0,1,1,0,1,1,0,0,0,1,209);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (50,'Jumbo Space Travel','Eric Schiavone',0,0,0,0,1,0,0,1,1,0,0,1,697);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (51,'Just Cruises, Inc.','Facondo Pugliesi',0,0,0,1,0,1,0,1,1,1,1,0,1479);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (52,'Karma','Ferdinand Santiago Zamudio',0,0,0,0,1,1,0,0,1,0,0,0,2750);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (53,'Key To Travel','Ferragus Laisné',0,0,0,0,0,1,1,0,1,1,0,0,2831);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (54,'La Bussola','Fletcher Paradis',0,0,0,1,0,1,0,1,0,1,0,1,1342);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (55,'La Nuova Rotta','Gabriel L. Dement',0,0,0,0,0,0,0,0,1,0,1,0,1812);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (56,'La Rotonda','Gaetano Li Fonti',0,0,0,0,1,1,1,0,0,1,0,1,1698);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (57,'La Vela','Gaspare Sabbatini',0,0,0,1,0,0,1,1,0,1,0,0,1350);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (58,'Le Soleil','Ghaith Majid al Din Said',0,0,0,1,1,0,0,0,0,0,0,1,936);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (59,'Leading Landings','Hipķlito Gaytan Peres',0,0,0,1,1,1,1,0,1,0,0,1,2080);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (60,'Locageta Travels','Iber Herrera Hidalgo',0,0,0,0,1,0,1,0,1,1,1,0,1320);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (61,'Loring Agence De Voyage','Indro Lo Duca',0,0,0,0,1,0,1,1,1,1,1,0,201);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (62,'Mambo Salentino','Isabela Ribeiro Souza',1,4,8000,1,1,1,0,0,1,1,1,1,1843);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (63,'Mapa Viajero','Jana Probst',1,4,10000,0,1,1,0,0,1,0,0,1,754);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (64,'Marco Polo Viaggi','Jérôme Jomphe',0,0,0,1,0,1,0,0,0,1,1,0,1472);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (65,'Maya','John C. Maurer',0,0,0,0,1,0,0,0,0,0,0,0,2355);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (66,'Michelino Tours','Joy J. Henderson',0,0,0,1,1,1,0,1,1,1,1,0,2962);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (67,'Mundo Imperial','Julia Carvalho Pinto',0,0,0,0,1,0,0,0,1,1,0,1,2358);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (68,'Nilde Fiera Travel','Julia Wechsler',1,1,2100,1,0,1,1,1,0,0,0,1,1427);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (69,'Nōmada Tours','Júlio Araujo Alves',1,3,6900,1,0,1,0,1,0,1,1,0,1224);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (70,'Outside Outfitters','Kahil Shafeeq Khoury',0,0,0,1,0,1,0,1,1,0,0,0,1878);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (71,'Paso De Viaje','Kai Swift',0,0,0,1,1,0,0,1,0,1,0,1,219);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (72,'Petra Viaggi','Karin Bumgarner',0,0,0,0,0,0,0,1,0,0,1,0,1209);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (73,'Planes And Trains Travel','Kauan Rodrigues Barbosa',0,0,0,1,1,1,0,0,1,1,0,1,670);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (74,'Relax And Unwind','Khayriyyah Sibaal Said',1,2,5500,1,1,0,0,1,0,1,0,1,985);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (75,'Road Less Traveled','Laura Azevedo Alves',0,0,0,0,1,0,0,1,1,1,1,1,636);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (76,'Seaquid Travel & Tours','Lenora Urrútia Anaya',0,0,0,1,0,1,1,0,0,1,1,0,1080);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (77,'Sin Fronteras','Lisa Schmidt',0,0,0,0,0,0,1,1,0,0,0,1,1677);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (78,'Start To Finish','Maddalena Lori',0,0,0,0,0,1,0,0,0,0,1,1,2770);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (79,'The Best Agency','Madeeha Karam Mansour',1,2,4800,0,0,0,1,1,1,1,0,1,405);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (80,'Travel BloggerS Paradise','Magdalena D. Bhakta',0,0,0,1,1,1,0,0,0,0,0,1,1029);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (81,'Travel To Go','Maia Piazza',1,0,0,1,1,1,1,0,1,0,0,0,443);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (82,'Travel Tricks','Mallory Demers',0,0,0,1,1,1,0,1,0,1,1,0,2433);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (83,'Travelsphere','Maria Luisa Pinto',0,0,0,0,0,1,1,1,1,0,1,0,208);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (84,'Travesėa Express','Marilyn D. Standridge',0,0,0,1,1,1,1,0,1,0,1,1,2185);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (85,'Trips To Travel','Mario Ackerman',1,3,3800,1,0,0,1,1,0,1,0,0,1487);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (86,'Turisfront (Tutrismo Sin Fronteras)','Mario G. King',0,0,0,1,0,1,0,0,1,1,0,1,413);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (87,'Una Vita In Viaggio','Matheus Fernandes Oliveira',0,0,0,1,0,0,1,0,0,0,1,0,677);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (88,'Vacances J''Oublie Tout','Michela Calabresi',0,0,0,0,0,1,0,0,0,1,1,1,985);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (89,'Vacanziamo','Mu''nisah Shuruq Masih',0,0,0,0,0,0,1,0,1,0,1,1,1666);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (90,'Valentine Voyages','Nafeesa Radwa Khouri',0,0,0,0,0,1,0,1,1,0,0,0,2793);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (91,'Viaggi Al Femminile','Patrica J. Singer',0,0,0,1,1,0,0,1,1,0,1,0,2410);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (92,'Viaggi Palma','Rafaela Gomes Fernandes',0,0,0,0,0,1,1,0,0,1,1,0,2116);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (93,'Viaggia Che Ti Passa','Samaah Taalah Antar',0,0,0,1,0,0,0,0,1,1,0,1,2248);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (94,'Viaja Y Vive','Sarah Blackburn',0,0,0,0,1,1,0,1,0,0,0,1,2640);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (95,'Viajes Cosmōpolis','Talon Allaire',0,0,0,1,0,1,1,0,0,0,0,0,955);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (96,'Vive Ahora','Tanya E. Madsen',0,0,0,0,1,1,0,0,1,1,0,0,480);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (97,'Vuelta Total','Thomas Greenwood',0,0,0,0,0,0,0,0,0,1,0,1,402);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (98,'Weite Welt','Tyler Buckley',0,0,0,1,1,1,0,1,1,1,0,0,658);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (99,'Where To Travel?','Ulderico Sagese',0,0,0,1,1,1,1,0,1,0,1,1,1113);
INSERT INTO agenzie(Codice,Nome_Agenzia,Nome_Referente,Preventivi_01,Num_Prenotazioni,Fatturato_netto,Cicloturismo,Enogastronomia,LGBT,Pet_friendly,Piccoli_gruppi,Lune_di_miele,ArteCultura,BenessereBellezza,MICE,Prezzo) VALUES (100,'World Wide Explorers','Yasmin Stone',0,0,0,0,1,0,0,1,0,0,0,0,269);

CREATE TABLE IF NOT EXISTS referenti(
   Codice         INTEGER  NOT NULL PRIMARY KEY 
  ,Nome_e_cognome VARCHAR(28) NOT NULL
  ,telefono       VARCHAR(15) NOT NULL
  ,email          VARCHAR(39) NOT NULL
  ,lingua         VARCHAR(4) NOT NULL
  ,fiera          VARCHAR(21) NOT NULL
);
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (1,'Abbie McCarthy','070 1203 9510','AbbieMcCarthy@rhyta.com','ENG','WTM (Londra) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (2,'Abdul-Ahad Bakr Nader','72 154 600','Abdul-AhadBakrNader@jourrapide.com','ENG','ATM (Dubai) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (3,'Abdul-Qadir Salamah Nazari','73 849 704','Abdul-QadirSalamahNazari@armyspy.com','ENG','ATM (Dubai) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (4,'Abi Medrano Montez','787 779 789','AbiMedranoMontez@teleworm.us','TED','ITB (Berlino) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (5,'Abida Juwan Bazzi','75 946 974','AbidaJuwanBazzi@jourrapide.com','ENG','ATM (Dubai) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (6,'Abigail Feakes','(03) 5337 0191','AbigailFeakes@dayrep.com','ENG','WTM (Londra) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (7,'Aceline Tétrault','01.46.96.04.88','AcelineTetrault@rhyta.com','FRA','IFTM (Parigi) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (8,'Adalgiso Sabbatini','0349 1511270','AdalgisoSabbatini@teleworm.us','ITA','BTM (Lecce) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (9,'Adele Sagese','0364 3937420','AdeleSagese@teleworm.us','ITA','TTG (Rimini) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (10,'Agate Quiron','03.11.77.31.09','AgateQuiron@jourrapide.com','FRA','B2B (Bari) 2019');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (11,'Agostina Li Fonti','0330 9007793','AgostinaLiFonti@armyspy.com','ITA','TTG (Rimini) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (12,'Aimee Mitchell','070 5971 0785','AimeeMitchell@dayrep.com','ENG','PLE (Marrakech) 2019');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (13,'Al Tijani ''Awf Koury','73 765 880','AlTijaniAwfKoury@teleworm.us','ENG','ATM (Dubai) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (14,'Alda Conti','0368 0523948','AldaConti@jourrapide.com','ITA','BTM (Lecce) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (15,'Ale Abrego Garza','752 887 929','AleAbregoGarza@teleworm.us','SPA','IFEMA (Madrid) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (16,'Aleandro Marino','0318 3591278','AleandroMarino@dayrep.com','ITA','TTG (Rimini) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (17,'Aleksander Zambrano Olivárez','662 296 588','AleksanderZambranoOlivarez@dayrep.com','SPA','IFEMA (Madrid) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (18,'Alex Souza Martins','21 258 698 0682','AlexSouzaMartins@teleworm.us','POR','PLE (Marrakech) 2019');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (19,'Alexander Graham','079 4642 5811','AlexanderGraham@teleworm.us','ENG','WTM (Londra) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (20,'Alfonso De Luca','0394 3723612','AlfonsoDeLuca@armyspy.com','ITA','B2B (Bari) 2019');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (21,'Alfredina Bellucci','0353 1148748','AlfredinaBellucci@armyspy.com','ITA','B2B (Bari) 2019');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (22,'Alicia Hargreaves','079 5942 9686','AliciaHargreaves@dayrep.com','ENG','WTM (Londra) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (23,'Alicia James','078 4267 1210','AliciaJames@dayrep.com','ENG','WTM (Londra) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (24,'Amber Mullaly','0680 331 96 21','AmberMullaly@rhyta.com','TED','ITB (Berlino) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (25,'Ambra Longo','0371 7332407','AmbraLongo@jourrapide.com','ITA','B2B (Bari) 2019');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (26,'Ana Delgado Ortega','711 759 163','AnaDelgadoOrtega@rhyta.com','SPA','IFEMA (Madrid) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (27,'Ana Ferreira Alves','21 284 641 4681','AnaFerreiraAlves@dayrep.com','POR','PLE (Marrakech) 2019');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (28,'Andrea Urner','06435 34 99 25','AndreaUrner@armyspy.com','TED','ITB (Berlino) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (29,'Annett Kalb','04758 36 43 77','AnnettKalb@teleworm.us','TED','ITB (Berlino) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (30,'Artus Lanteigne','01.99.58.63.19','ArtusLanteigne@rhyta.com','FRA','IFTM (Parigi) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (31,'Austin Ashton','(03) 9375 3154','AustinAshton@jourrapide.com','ENG','WTM (Londra) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (32,'Barbara C. Franco','09403 23 60 99','BarbaraCFranco@jourrapide.com','TED','ITB (Berlino) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (33,'Basilio Bianchi','0361 8151498','BasilioBianchi@armyspy.com','ITA','B2B (Bari) 2019');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (34,'Benvenuto Zito','0383 4345458','BenvenutoZito@armyspy.com','ITA','TTG (Rimini) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (35,'Callum Bryant','077 1357 6390','CallumBryant@teleworm.us','ENG','WTM (Londra) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (36,'Carina Aguilera Saldana','636 207 254','CarinaAguileraSaldana@teleworm.us','SPA','IFEMA (Madrid) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (37,'Carl S. Franklin','354 436 5199','CarlSFranklin@rhyta.com','ENG','WTM (Londra) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (38,'Carla Martins Silva','21 289 188 5816','CarlaMartinsSilva@dayrep.com','POR','PLE (Marrakech) 2019');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (39,'Connie R. Krueger','9376 4333','ConnieRKrueger@rhyta.com','ENG','WTM (Londra) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (40,'Doda Monaldo','0344 8498039','DodaMonaldo@dayrep.com','ITA','B2B (Bari) 2019');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (41,'Dominic Warren','079 6952 7719','DominicWarren@rhyta.com','ENG','WTM (Londra) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (42,'Donald A. Long','73 670 898','DonaldALong@rhyta.com','ENG','WTM (Londra) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (43,'Dylan Miller','079 3146 1318','DylanMiller@teleworm.us','ENG','WTM (Londra) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (44,'Edna B. Lee','48 51 546 72 80','EdnaBLee@teleworm.us','ENG','WTM (Londra) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (45,'Elliot George','078 2970 2166','ElliotGeorge@dayrep.com','ENG','WTM (Londra) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (46,'Emanuela Iadanza','0314 3528349','EmanuelaIadanza@armyspy.com','ITA','TTG (Rimini) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (47,'Emilly Barros Alves','21 218 709 7148','EmillyBarrosAlves@rhyta.com','POR','PLE (Marrakech) 2019');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (48,'Emily Castro Oliveira','21 295 484 3154','EmilyCastroOliveira@dayrep.com','POR','PLE (Marrakech) 2019');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (49,'Emmanuelle Paulet','02.09.03.14.88','EmmanuellePaulet@teleworm.us','FRA','IFTM (Parigi) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (50,'Eric Schiavone','0398 5999248','EricSchiavone@teleworm.us','SPA','IFEMA (Madrid) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (51,'Facondo Pugliesi','0342 8497550','FacondoPugliesi@teleworm.us','ITA','BTM (Lecce) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (52,'Ferdinand Santiago Zamudio','796 052 976','FerdinandSantiagoZamudio@rhyta.com','SPA','IFEMA (Madrid) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (53,'Ferragus Laisné','01.49.58.56.58','FerragusLaisne@jourrapide.com','FRA','ILTM (Cannes) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (54,'Fletcher Paradis','04.03.77.97.60','FletcherParadis@rhyta.com','FRA','ILTM (Cannes) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (55,'Gabriel L. Dement','96 589848','GabrielLDement@rhyta.com','ENG','WTM (Londra) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (56,'Gaetano Li Fonti','0393 8679204','GaetanoLiFonti@dayrep.com','ITA','TTG (Rimini) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (57,'Gaspare Sabbatini','0365 0391771','GaspareSabbatini@armyspy.com','ITA','TTG (Rimini) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (58,'Ghaith Majid al Din Said','75 237 023','GhaithMajidalDinSaid@dayrep.com','ENG','ATM (Dubai) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (59,'Hipķlito Gaytan Peres','687 834 160','HipolitoGaytanPeres@teleworm.us','SPA','PLE (Marrakech) 2020');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (60,'Iber Herrera Hidalgo','665 984 564','IberHerreraHidalgo@dayrep.com','SPA','IFEMA (Madrid) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (61,'Indro Lo Duca','0312 7796899','IndroLoDuca@dayrep.com','ITA','BTM (Lecce) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (62,'Isabela Ribeiro Souza','21 222 183 9610','IsabelaRibeiroSouza@teleworm.us','POR','PLE (Marrakech) 2019');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (63,'Jana Probst','0911 63 57 90','JanaProbst@armyspy.com','TED','ITB (Berlino) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (64,'Jérôme Jomphe','03.67.67.22.48','JeromeJomphe@teleworm.us','FRA','ILTM (Cannes) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (65,'John C. Maurer','299 33 90 30','JohnCMaurer@jourrapide.com','ENG','WTM (Londra) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (66,'Joy J. Henderson','39 0371 4633606','JoyJHenderson@rhyta.com','ITA','TTG (Rimini) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (67,'Julia Carvalho Pinto','21 239 106 6906','JuliaCarvalhoPinto@rhyta.com','POR','PLE (Marrakech) 2019');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (68,'Julia Wechsler','06724 26 55 71','JuliaWechsler@jourrapide.com','TED','ITB (Berlino) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (69,'Júlio Araujo Alves','21 227 660 3911','JulioAraujoAlves@dayrep.com','POR','PLE (Marrakech) 2019');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (70,'Kahil Shafeeq Khoury','78 853 310','KahilShafeeqKhoury@armyspy.com','ENG','ATM (Dubai) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (71,'Kai Swift','077 0037 1921','KaiSwift@dayrep.com','ENG','WTM (Londra) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (72,'Karin Bumgarner','04177 98 22 50','KarinBumgarner@teleworm.us','TED','ITB (Berlino) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (73,'Kauan Rodrigues Barbosa','21 265 983 4222','kauanRodriguesBarbosa@rhyta.com','POR','PLE (Marrakech) 2019');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (74,'Khayriyyah Sibaal Said','78 367 843','KhayriyyahSibaalSaid@rhyta.com','ENG','ATM (Dubai) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (75,'Laura Azevedo Alves','21 265 382 5689','LauraAzevedoAlves@jourrapide.com','POR','PLE (Marrakech) 2019');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (76,'Lenora Urrútia Anaya','716 306 641','LenoraUrrutiaAnaya@jourrapide.com','SPA','PLE (Marrakech) 2021');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (77,'Lisa Schmidt','036929 22 75','LisaSchmidt@dayrep.com','TED','ITB (Berlino) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (78,'Maddalena Lori','0359 9845727','MaddalenaLori@armyspy.com','ITA','TTG (Rimini) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (79,'Madeeha Karam Mansour','78 376 068','MadeehaKaramMansour@armyspy.com','ENG','ATM (Dubai) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (80,'Magdalena D. Bhakta','31 06-56021342','MagdalenaDBhakta@dayrep.com','ENG','WTM (Londra) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (81,'Maia Piazza','0364 2667675','MaiaPiazza@jourrapide.com','ITA','TTG (Rimini) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (82,'Mallory Demers','01.37.75.22.54','MalloryDemers@rhyta.com','FRA','IFTM (Parigi) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (83,'Maria Luisa Pinto','0329 8464415','MariaLuisaPinto@rhyta.com','ITA','TTG (Rimini) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (84,'Marilyn D. Standridge','735 912 283','MarilynDStandridge@armyspy.com','ENG','WTM (Londra) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (85,'Mario Ackerman','07062 40 13 95','MarioAckerman@rhyta.com','TED','ITB (Berlino) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (86,'Mario G. King','03.12.81.06.44','MarioGKing@armyspy.com','FRA','IFTM (Parigi) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (87,'Matheus Fernandes Oliveira','21 214 658 0997','MatheusFernandesOliveira@jourrapide.com','POR','PLE (Marrakech) 2019');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (88,'Michela Calabresi','0380 8958658','MichelaCalabresi@dayrep.com','ITA','TTG (Rimini) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (89,'Mu''nisah Shuruq Masih','76 495 492','MunisahShuruqMasih@armyspy.com','ENG','ATM (Dubai) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (90,'Nafeesa Radwa Khouri','73 293 180','NafeesaRadwaKhouri@rhyta.com','ENG','ATM (Dubai) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (91,'Patrica J. Singer','046 334 4506','PatricaJSinger@dayrep.com','ENG','WTM (Londra) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (92,'Rafaela Gomes Fernandes','21 234 842 0043','RafaelaGomesFernandes@jourrapide.com','POR','PLE (Marrakech) 2019');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (93,'Samaah Taalah Antar','78 993 474','SamaahTaalahAntar@teleworm.us','ENG','ATM (Dubai) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (94,'Sarah Blackburn','077 8668 8067','SarahBlackburn@armyspy.com','ENG','WTM (Londra) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (95,'Talon Allaire','04.61.76.89.71','TalonAllaire@jourrapide.com','FRA','ILTM (Cannes) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (96,'Tanya E. Madsen','832-937-7202','TanyaEMadsen@teleworm.us','ENG','WTM (Londra) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (97,'Thomas Greenwood','077 8264 3818','ThomasGreenwood@armyspy.com','ENG','WTM (Londra) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (98,'Tyler Buckley','078 6746 1401','TylerBuckley@dayrep.com','ENG','WTM (Londra) 2018');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (99,'Ulderico Sagese','0385 1630020','UldericoSagese@dayrep.com','ITA','B2B (Bari) 2019');
INSERT INTO referenti(Codice,Nome_e_cognome,telefono,email,lingua,fiera) VALUES (100,'Yasmin Stone','078 2002 9470','YasminStone@teleworm.us','ENG','ATM (Dubai) 2018');
